### ISSUE TITLE
LinkedIn

### ISSUE THREAD

**Issue by tayler-ramsay** [nicolasbeauvais/vue-social-sharing#221] opened 2020-05-22 19:19 UTC
I see you updated the Linkedin url recently... It is erring every-time  I launch the window to share

**Comment by nicolasbeauvais** [comment] 2020-05-23 11:05
Hello @tayler-ramsay, could you be more precise on what's wrong on your end?
It works fine on the demo https://nicolasbeauvais.github.io/vue-social-sharing/?path=/story/vuesocialsharing--multiple-share-networks

**Comment by tayler-ramsay** [comment] 2020-05-23 14:22
@nicolasbeauvais sorry... I have attached a screen shot. It could very well be on my end. I'v tried it in chrome and safari. I know it says its on there end I just didn't know if something was not getting set right.


![Screen Shot 2020-05-23 at 10 18 28 AM](https://user-images.githubusercontent.com/5311889/82733037-1e681880-9cdf-11ea-97da-2e901c890799.png)

**Comment by nicolasbeauvais** [comment] 2020-05-23 14:48
@tayler-ramsay could you write here the property that you used (url, title, description...)? It might be a formatting issue.

**Comment by tayler-ramsay** [comment] 2020-05-25 20:08
`    
             <ShareNetwork
                network="LinkedIn"
                :url="url"
                :title="title"
                :description="description"
              >
`

**Comment by KonradDeskiewicz** [comment] 2020-05-28 08:29
Got a similar issue. Didn't test it extensively yet, but first what comes into mind is that Linkedin is checking OG tags upon opening its iframe, and if URL is not accessible it returns an error. Same goes for Facebook if I try to share `localhost` URL

**Comment by tayler-ramsay** [comment] 2020-06-01 17:52
Thank you for the response have you had any luck with this yet?

**Comment by nicolasbeauvais** [comment] 2020-06-03 23:25
@tayler-ramsay the link you shared (https://www.versatilecredit.com/blog/the-power-of-second-look-financing) just load infinitely on my browser, the LinkedIn og tag inspector can't access it either https://www.linkedin.com/post-inspector/inspect/https:%2F%2Fwww.versatilecredit.com%2Fblog%2Fthe-power-of-second-look-financing

I'm closing this issue as the problem is on your end and not related to Vue Social Sharing.

Thank you @KonradDeskiewicz for the help.

**Closed by nicolasbeauvais** 2020-06-03 23:25 UTC
