### ISSUE TITLE
WhatsApp share not working

### ISSUE THREAD

**Issue by haris0** [nicolasbeauvais/vue-social-sharing#80] opened 2018-02-28 10:44 UTC
Why WhatsApp share not working?
in your demo in https://nicolasbeauvais.github.io/vue-social-sharing/ is not working too

**Comment by nicolasbeauvais** [comment] 2018-02-28 21:44
Works on my android phone with WhatsApp installed. What device did you use for your test?

**Comment by haris0** [comment] 2018-03-01 05:17
ohh, whatsapp share work if accessed with gadgets?
can it work when i access with pc browser?

**Comment by nicolasbeauvais** [comment] 2018-03-01 08:42
Telegram works well on PC but not WhatsApp and Viber as their sharing url look like this:
`whatsapp://send?text=@description%0D%0A@url`
I'm closing the issue as this is not a bug, Feel free to re-open if you find something interesting to share WhatsApp from a PC browser.

**Comment by haris0** [comment] 2018-03-02 03:50
how about using `https://api.whatsapp.com/send?text=@description%0D%0A@url`
other web using this link to share WhatsApp from a PC browser, but i'm confused how to implement in this plugin.
can it implement to this plugin?

**Comment by MaraniMatias** [comment] 2018-12-11 21:46
You can see [Extending the network list](https://github.com/nicolasbeauvais/vue-social-sharing#extending-the-network-list)

I using
```html
<network   network="whatsappFix" ><i class="icon ion-logo-whatsapp"></i></network>
```

```javascript
      whatsappFix: {
        sharer: `https://api.whatsapp.com/send?text=Apunte: _*${
          this.title
        }*_ (cod ${this.cod})%0D%0A@quote`,
        type: "popup",
        action: "share/whatsapp/share"
      }
```

**Closed** 2019-02-11 00:31 UTC
Labels: enhancement

**Comment by peoray** [comment] 2019-05-28 12:35
> You can see [Extending the network list](https://github.com/nicolasbeauvais/vue-social-sharing#extending-the-network-list)
> 
> I using
> 
> ```
> <network   network="whatsappFix" ><i class="icon ion-logo-whatsapp"></i></network>
> ```
> 
> ```js
> whatsappFix: {
>   sharer: `https://api.whatsapp.com/send?text=Apunte: _*${this.title}*_%0D%0A@quote`,
>   type: "popup",
>   action: "share/whatsapp/share"
> }
> ```

@MaraniMatias Where did you add the `whatsappFix` object property?
